server:
  port: 3344

spring:
  application:
    name: microservicecloud-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/LittleMeiko/mircroservicecloud-config.git #GitHub上git仓库的名字
          default-label: main
